apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: christophemoreira-com-tls
spec:
  secretName: christophemoreira-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: christophemoreira.com
  dnsNames:
    - christophemoreira.com
    - www.christophemoreira.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - christophemoreira.com
          - wwww.christophemoreira.com
