apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # remove /api/ from route
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: myportofolio-service
              servicePort: 3000
          - path: /robotfriends/
            backend:
              serviceName: robotfriends-service
              servicePort: 3001
          - path: /yelpcamp/
            backend:
              serviceName: yelpcamp-service
              servicePort: 3002
          - path: /facerecognition/
            backend:
              serviceName: facerecognition-service
              servicePort: 3003
